# See https://jekyllrb.com/docs/configuration/ for more information about configuration settings

title: JonJam // Side Quests
author: Jonathan Harrison
description: >- # this means to ignore newlines until "baseurl:"
  Engineering notes, experiments and the occasional gaming obsession.

# Social
github_username: jonjam
linkedin_username: jonjam

# Site settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "jonjam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
theme: minima
show_excerpts: true

# Plugins
plugins:
  - jekyll-feed
